apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  namespace: csmvck8s-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-api
  template:
    metadata:
      labels:
        app: gateway-service-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: gateway-service-api
        image: ozanalcanoglu/cs-gateway-service:latest
        ports:
        - containerPort: 8080
        env:
          # JWT Ayarları
          - name: JwtSettings__Secret
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
          - name: JwtSettings__Issuer
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: JWT_ISSUER
          - name: JwtSettings__Audience
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: JWT_AUDIENCE
          
          # Observability
          - name: OTLP_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: OTLP_ENDPOINT
          - name: SEQ_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SEQ_URL
          
          # Servis URL'leri
          - name: AUTH_SERVICE_URL
            value: "http://auth-service-api.csmvck8s-ns.svc.cluster.local:8080"
          - name: USER_SERVICE_URL
            value: "http://user-service-api.csmvck8s-ns.svc.cluster.local:8080"
          - name: PRODUCT_SERVICE_URL
            value: "http://product-service-api.csmvck8s-ns.svc.cluster.local:8080"
          
          # Diğer
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-api
  namespace: csmvck8s-ns
spec:
  selector:
    app: gateway-service-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP