apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: csmvck8s-ns
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      logging:
        loglevel: debug
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [logging, prometheus]
        traces:
          receivers: [otlp]
          exporters: [logging]